# Visit https://golangci-lint.run/ for usage documentation
# and information on other useful linters
version: "2"

run:
  timeout: "3m"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  disable:
    - arangolint
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - iface
    - importas
    - inamedparam
    - interfacebloat
    - intrange
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - mirror
    - mnd
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - tagalign
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - tparallel
    - unparam
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
    - zerologlint
  enable:
    - durationcheck
    - errcheck
    # - forcetypeassert
    # - godot
    - ineffassign
    - makezero
    - misspell
    # - nilerr
    # - predeclared
    - staticcheck
    - unconvert
    # - unparam
    - unused
    - govet
    - nolintlint

  settings:
    errcheck:
      exclude-functions:
        - (*github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.ResourceData).Set
        - fmt.Fprintln
        - (io.Closer).Close
    staticcheck:
      checks:
        - '-QF1001'
        - '-QF1003'
        - '-QF1004'
        - '-QF1008'
        - '-QF1011'
        - '-SA1006'
        - '-ST1023'

formatters:
  settings:
    gofmt:
      simplify: true
