name: Dotcom Individual Acceptance Tests

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  acceptance-tests-individual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Acceptance Tests (Individual)
        id: acceptance-tests-individual
        run: ./scripts/entrypoint.sh
        env:
          RUN_ALL: 'false'
          TF_LOG: WARN
          GITHUB_OWNER: gh-terraform-provider-tester
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_TEST_ORGANIZATION: backmarket-sandbox-yli
          GITHUB_TEST_OWNER: gh-terraform-provider-tester
          GITHUB_TEST_USER_TOKEN: ${{ secrets.TEST_USER_TOKEN_INDIVIDUAL }}
          GITHUB_TOKEN: ${{ secrets.TEST_USER_TOKEN_INDIVIDUAL }}
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 245841152
