name: Dotcom Acceptance Tests (manual)

on:
  pull_request:
    types: [labeled]

jobs:

  acceptance-tests-anonymous:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test/')
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Acceptance Tests (Anonymous)
        id: acceptance-tests-anonymous
        run: ./scripts/entrypoint.sh
        env:
          RUN_ALL: 'false' # Forces running all available tests
          TF_LOG: INFO # TF_LOG environment variable used during test runs
          GITHUB_BASE_URL: https://api.github.com/ # GitHub base URL to run tests against
          GITHUB_TEST_ORGANIZATION: terraformtesting # GitHub organization to support testing individual mode
          GITHUB_TEST_OWNER: github-terraform-test-user # GitHub owner to support testing organization mode
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module # Template Repository used to test creation during test runs
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 25117183 # Template Repository Release ID used during test runs
      - name: Failed Acceptance Tests (Anonymous)
        if: ${{ failure() }}
        run: ./scripts/entrypoint.sh
        with:
          RUN_ALL: 'false'
          TF_LOG: DEBUG
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_TEST_ORGANIZATION: terraformtesting
          GITHUB_TEST_OWNER: github-terraform-test-user
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 25117183


  acceptance-tests-individual:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test')
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Acceptance Tests (Individual)
        id: acceptance-tests-individual
        run: ./scripts/entrypoint.sh
        env:
          RUN_ALL: 'false'
          TF_LOG: INFO
          GITHUB_OWNER: github-terraform-test-user # GitHub Owner to run tests as
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_TEST_ORGANIZATION: terraformtesting
          GITHUB_TEST_OWNER: github-terraform-test-user
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }} # Authentication for GitHub user to run tests as
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 25117183
      - name: Failed Acceptance Tests (Individual)
        id: acceptance-tests-individual
        run: ./scripts/entrypoint.sh
        if: ${{ failure() }}
        with:
          RUN_ALL: 'false'
          TF_LOG: DEBUG
          GITHUB_OWNER: github-terraform-test-user
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_TEST_ORGANIZATION: terraformtesting
          GITHUB_TEST_OWNER: github-terraform-test-user
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 25117183

  acceptance-tests-organization:
    runs-on: ubuntu-latest
    if: contains(join(github.event.pull_request.labels.*.name, ', '), 'test')
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Acceptance Tests (Organization)
        id: acceptance-tests-organization
        run: ./scripts/entrypoint.sh
        env:
          RUN_ALL: 'false'
          TF_LOG: INFO
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_ORGANIZATION: terraformtesting # GitHub Organization to run tests as
          GITHUB_TEST_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_OWNER: github-terraform-test-user
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 25117183

      - name: Failed Acceptance Tests (Organization)
        run: ./scripts/entrypoint.sh
        if: ${{ failure() }}
        with:
          RUN_ALL: 'false'
          TF_LOG: DEBUG
          GITHUB_BASE_URL: https://api.github.com/
          GITHUB_ORGANIZATION: terraformtesting
          GITHUB_TEST_ORGANIZATION: terraformtesting
          GITHUB_TEST_USER_TOKEN: ${{ secrets.DOTCOM_TEST_USER_TOKEN }}
          GITHUB_TEST_OWNER: github-terraform-test-user
          GITHUB_TEMPLATE_REPOSITORY: terraform-template-module
          GITHUB_TEMPLATE_REPOSITORY_RELEASE_ID: 25117183
